### ISSUE TITLE
运行 main.py文件 显示  “进程已结束，退出代码为 -1073741819 (0xC0000005)”

### ISSUE THREAD

**Issue by woshidamow5534** [YOLOSHOW/YOLOSHOW#36]
运行 main.py文件 显示  “进程已结束，退出代码为 -1073741819 (0xC0000005)”  有没有好兄弟指导一下

**Comment by LiuQP11** [comment]
我也遇到了同样的问题，希望有大佬能指点一下

**Comment by chenhahashao** [comment]
我也是

**Comment by charon525** [comment]
我刚刚稍微修改了一下，现在显示其他错误了(不知道是否可行
![image](https://github.com/user-attachments/assets/5945a97c-1ddc-43fc-b687-e252aac4f6e3)

**Comment by SwimmingLiu** [comment]
十分抱歉，由于最近忙于论文实验，没有及时维护仓库。明天我将会发布 `YOLOSHOW v4.0`， 支持YOLOv11新模型，同时优化了代码结构和兼容最新版本的 `ultralytics`

**Comment by SwimmingLiu** [comment]
再次为未及时修复仓库的bug而感到抱歉，目前 `YOLOSHOW v4.1` 已推送至仓库，请各位更新代码并查验。

**Comment by KandyYe** [comment]
我抓了最新的代码还是存在这个问题，请问大伙的问题解决了吗？

**Comment by SwimmingLiu** [comment]
> 我抓了最新的代码还是存在这个问题，请问大伙的问题解决了吗？

有尝试过重新创建新的虚拟环境吗？

**Comment by SwimmingLiu** [comment]
> 我抓了最新的代码还是存在这个问题，请问大伙的问题解决了吗？

辛苦把运行的结果和conda环境截图发送至我的邮箱[SwimmingLiu@outlook.com](mailto:SwimmingLiu@outlook.com) , 我需要复现相同的失败结果才能找到bug的源头。

**Comment by chenhahashao** [comment]
大佬能帮忙看看这个问题吗
![image](https://github.com/user-attachments/assets/48fa3f38-3de1-40b5-80f7-1eca941883fd)
![image](https://github.com/user-attachments/assets/a7d1e5ab-c173-4353-8996-965eaa545d77)

**Comment by SwimmingLiu** [comment]
@chenhahashao `git pull` 拉取今天下午最新的代码 (YOLOSHOW v4.3)

**Comment by KandyYe** [comment]
> > 我抓了最新的代码还是存在这个问题，请问大伙的问题解决了吗？
> 
> 有尝试过重新创建新的虚拟环境吗？

刚刚重新创建了虚拟环境，这个问题已经解决了。非常感谢！

**Comment by chenhahashao** [comment]
可以了感谢大佬
